/* File generated by the BNF Converter (bnfc 2.9.4). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Prog  pProg(FILE *inp);
Prog psProg(const char *str);
Id  pId(FILE *inp);
Id psId(const char *str);
Ident_type  pIdent_type(FILE *inp);
Ident_type psIdent_type(const char *str);
Dec  pDec(FILE *inp);
Dec psDec(const char *str);
Label  pLabel(FILE *inp);
Label psLabel(const char *str);
Uses  pUses(FILE *inp);
Uses psUses(const char *str);
Variable  pVariable(FILE *inp);
Variable psVariable(const char *str);
Type  pType(FILE *inp);
Type psType(const char *str);
Type_specifier  pType_specifier(FILE *inp);
Type_specifier psType_specifier(const char *str);
Constant  pConstant(FILE *inp);
Constant psConstant(const char *str);
Cmdlist  pCmdlist(FILE *inp);
Cmdlist psCmdlist(const char *str);
Cmd  pCmd(FILE *inp);
Cmd psCmd(const char *str);
Cmd_type  pCmd_type(FILE *inp);
Cmd_type psCmd_type(const char *str);
Exprecion  pExprecion(FILE *inp);
Exprecion psExprecion(const char *str);
Exp  pExp(FILE *inp);
Exp psExp(const char *str);
Exp  pExp2(FILE *inp);
Exp psExp2(const char *str);
Procedure  pProcedure(FILE *inp);
Procedure psProcedure(const char *str);

#endif
