/* File generated by the BNF Converter (bnfc 2.9.4). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitProg(Prog p);
void visitId(Id p);
void visitIdent_type(Ident_type p);
void visitDec(Dec p);
void visitLabel(Label p);
void visitUses(Uses p);
void visitVariable(Variable p);
void visitType(Type p);
void visitType_specifier(Type_specifier p);
void visitConstant(Constant p);
void visitCmdlist(Cmdlist p);
void visitCmd(Cmd p);
void visitCmd_type(Cmd_type p);
void visitExprecion(Exprecion p);
void visitExp(Exp p);
void visitProcedure(Procedure p);


void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

